name: first workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Package Manager
      run: sudo apt update
    - name: Install JDK
      run: sudo apt install -y openjdk-17-jdk openjdk-17-jre
    - name: Hello
      run: echo Hello there!!!
    - name: Show Java Version
      run: java -version
    - name: Show directory name
      run: pwd
    - name: Show directory content
      run: ls
    #- name: Code Checkout
    #  uses: actions/checkout@v2
    - name: Clone from Git
      run: git clone https://github.com/md-supervisor/demo-ci.git
    - name: Show directory name
      run: pwd
    - name: Change directory
      run: cd demo-ci
    - name: Show directory name
      run: pwd
    - name: Show directory content again
      run: ls
    - name: Show build.gradle
      run: |
        cd demo-ci
        cat build.gradle
    - name: Gradle Permissions
      run: sudo chmod +x demo-ci/gradlew
    - name: Gradle Init
      run: demo-ci/gradlew init
    - name: Gradle Tasks
      run: demo-ci/gradlew tasks
    - name: Gradle Build
      run: demo-ci/gradlew build
    - name: Gradle Tasks
      run: demo-ci/gradlew tasks
    #- name: Gradle Test
    #  run: demo-ci/gradlew test
