name: first workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Hello
      run: echo Hello there!!!
    - name: Update Package Manager
      run: sudo apt update
    - name: Install JDK
      # run: sudo apt install -y default-jdk
      run: sudo apt install -y openjdk-17-jdk openjdk-17-jre
    - name: Show Java Version
      run: java -version
