name: first workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Package Manager
      run: sudo apt update
    - name: Install JDK
      run: sudo apt install -y openjdk-17-jdk openjdk-17-jre
    - name: Hello
      run: echo Hello there!!!
    - name: Show Java Version
      run: java -version
    - name: Show directory name
      run: pwd
    - name: Show directory content
      run: ls
    - name: Clone from Git
      run: git clone https://github.com/md-supervisor/demo-ci.git
    - name: Change directory
      run: cd demo-ci
    - name: Show directory content again
      run: ls
    - name: Show build.gradle
      run: cat build.gradle
